import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Shield, Smartphone, Key, Copy, Check, AlertCircle } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export default function TwoFactorAuth() {
  const [twoFactorEnabled, setTwoFactorEnabled] = useState(false);
  const [showSetupDialog, setShowSetupDialog] = useState(false);
  const [setupStep, setSetupStep] = useState<"method" | "qr" | "verify" | "backup">("method");
  const [selectedMethod, setSelectedMethod] = useState<"sms" | "authenticator">("authenticator");
  const [verificationCode, setVerificationCode] = useState("");
  const [backupCodes, setBackupCodes] = useState<string[]>([]);
  const [copiedCode, setCopiedCode] = useState<number | null>(null);

  // Mock QR code URL - in production, this would be generated by backend
  const qrCodeUrl = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
  const secretKey = "JBSWY3DPEHPK3PXP";

  const handleEnable2FA = () => {
    setShowSetupDialog(true);
    setSetupStep("method");
  };

  const handleMethodSelect = (method: "sms" | "authenticator") => {
    setSelectedMethod(method);
    if (method === "authenticator") {
      setSetupStep("qr");
    } else {
      // Send SMS code
      toast.success("Verification code sent to your phone");
      setSetupStep("verify");
    }
  };

  const handleVerifyCode = () => {
    if (verificationCode.length === 6) {
      // Mock verification
      toast.success("Code verified successfully!");
      // Generate backup codes
      const codes = Array.from({ length: 10 }, () => 
        Math.random().toString(36).substring(2, 10).toUpperCase()
      );
      setBackupCodes(codes);
      setSetupStep("backup");
    } else {
      toast.error("Please enter a 6-digit code");
    }
  };

  const handleFinishSetup = () => {
    setTwoFactorEnabled(true);
    setShowSetupDialog(false);
    toast.success("Two-factor authentication enabled!");
    setSetupStep("method");
    setVerificationCode("");
  };

  const handleDisable2FA = () => {
    setTwoFactorEnabled(false);
    toast.success("Two-factor authentication disabled");
  };

  const copyToClipboard = (text: string, index: number) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(index);
    toast.success("Copied to clipboard!");
    setTimeout(() => setCopiedCode(null), 2000);
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl text-[#0033A0] flex items-center gap-2">
            <Shield className="w-6 h-6" />
            Two-Factor Authentication
          </CardTitle>
          <CardDescription>
            Add an extra layer of security to your account
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Status Banner */}
          <div className={`p-4 rounded-lg border-2 ${
            twoFactorEnabled 
              ? "bg-green-50 border-green-300" 
              : "bg-amber-50 border-amber-300"
          }`}>
            <div className="flex items-start gap-3">
              {twoFactorEnabled ? (
                <Check className="w-5 h-5 text-green-600 mt-0.5" />
              ) : (
                <AlertCircle className="w-5 h-5 text-amber-600 mt-0.5" />
              )}
              <div className="flex-1">
                <p className={`font-semibold ${
                  twoFactorEnabled ? "text-green-900" : "text-amber-900"
                }`}>
                  {twoFactorEnabled ? "2FA is Active" : "2FA is Not Enabled"}
                </p>
                <p className={`text-sm mt-1 ${
                  twoFactorEnabled ? "text-green-700" : "text-amber-700"
                }`}>
                  {twoFactorEnabled 
                    ? "Your account is protected with two-factor authentication"
                    : "Enable 2FA to secure your account with an additional verification step"}
                </p>
              </div>
            </div>
          </div>

          {/* Enable/Disable Toggle */}
          <div className="flex items-center justify-between p-4 border rounded-lg">
            <div className="flex items-center gap-3">
              <Shield className="w-5 h-5 text-[#0033A0]" />
              <div>
                <Label className="font-medium cursor-pointer">
                  Two-Factor Authentication
                </Label>
                <p className="text-sm text-gray-500">
                  {twoFactorEnabled ? "Currently using Authenticator App" : "Require verification code on login"}
                </p>
              </div>
            </div>
            <Switch
              checked={twoFactorEnabled}
              onCheckedChange={(checked) => {
                if (checked) {
                  handleEnable2FA();
                } else {
                  handleDisable2FA();
                }
              }}
            />
          </div>

          {/* Security Info */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="font-semibold text-blue-900 mb-2 flex items-center gap-2">
              <Shield className="w-4 h-4" />
              Why Enable 2FA?
            </h4>
            <ul className="text-sm text-blue-800 space-y-1">
              <li>✅ Protects against unauthorized access</li>
              <li>✅ Prevents account takeover even if password is compromised</li>
              <li>✅ Secures your financial information and transactions</li>
              <li>✅ Meets industry security standards</li>
            </ul>
          </div>

          {/* Login Activity (if 2FA enabled) */}
          {twoFactorEnabled && (
            <div className="border-t pt-6">
              <h4 className="font-semibold text-gray-900 mb-3">Recent Login Activity</h4>
              <div className="space-y-3">
                <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div>
                    <p className="font-medium text-sm">Current Session</p>
                    <p className="text-xs text-gray-600">Chrome • New York, NY • Just now</p>
                  </div>
                  <span className="text-xs font-semibold text-green-600">ACTIVE</span>
                </div>
                <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div>
                    <p className="font-medium text-sm">Previous Login</p>
                    <p className="text-xs text-gray-600">iPhone • New York, NY • 2 days ago</p>
                  </div>
                  <span className="text-xs text-gray-500">2FA USED</span>
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Setup Dialog */}
      <Dialog open={showSetupDialog} onOpenChange={setShowSetupDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Set Up Two-Factor Authentication</DialogTitle>
            <DialogDescription>
              {setupStep === "method" && "Choose your preferred verification method"}
              {setupStep === "qr" && "Scan the QR code with your authenticator app"}
              {setupStep === "verify" && "Enter the verification code"}
              {setupStep === "backup" && "Save your backup codes"}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            {/* Step 1: Choose Method */}
            {setupStep === "method" && (
              <div className="space-y-3">
                <button
                  onClick={() => handleMethodSelect("authenticator")}
                  className="w-full p-4 border-2 rounded-lg hover:border-[#0033A0] hover:bg-blue-50 transition-colors text-left"
                >
                  <div className="flex items-center gap-3">
                    <Key className="w-6 h-6 text-[#0033A0]" />
                    <div>
                      <p className="font-semibold">Authenticator App</p>
                      <p className="text-sm text-gray-600">Use Google Authenticator or similar</p>
                    </div>
                  </div>
                </button>

                <button
                  onClick={() => handleMethodSelect("sms")}
                  className="w-full p-4 border-2 rounded-lg hover:border-[#0033A0] hover:bg-blue-50 transition-colors text-left"
                >
                  <div className="flex items-center gap-3">
                    <Smartphone className="w-6 h-6 text-[#0033A0]" />
                    <div>
                      <p className="font-semibold">SMS Text Message</p>
                      <p className="text-sm text-gray-600">Receive codes via text</p>
                    </div>
                  </div>
                </button>
              </div>
            )}

            {/* Step 2: QR Code */}
            {setupStep === "qr" && (
              <div className="space-y-4">
                <div className="text-center">
                  <div className="inline-block p-4 bg-white border-2 rounded-lg">
                    <img src={qrCodeUrl} alt="QR Code" className="w-48 h-48" />
                  </div>
                </div>
                <div className="bg-gray-50 p-3 rounded-lg">
                  <p className="text-xs text-gray-600 mb-2">Or enter this code manually:</p>
                  <div className="flex items-center gap-2">
                    <code className="flex-1 font-mono text-sm bg-white p-2 rounded border">
                      {secretKey}
                    </code>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => copyToClipboard(secretKey, -1)}
                    >
                      <Copy className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
                <Button onClick={() => setSetupStep("verify")} className="w-full">
                  Continue
                </Button>
              </div>
            )}

            {/* Step 3: Verify Code */}
            {setupStep === "verify" && (
              <div className="space-y-4">
                <div>
                  <Label>Enter 6-Digit Code</Label>
                  <Input
                    type="text"
                    placeholder="000000"
                    maxLength={6}
                    value={verificationCode}
                    onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, ""))}
                    className="text-center text-2xl font-mono tracking-widest"
                  />
                </div>
                <Button 
                  onClick={handleVerifyCode} 
                  className="w-full"
                  disabled={verificationCode.length !== 6}
                >
                  Verify Code
                </Button>
              </div>
            )}

            {/* Step 4: Backup Codes */}
            {setupStep === "backup" && (
              <div className="space-y-4">
                <div className="bg-amber-50 border border-amber-200 rounded-lg p-3">
                  <p className="text-sm text-amber-900 font-semibold mb-1">
                    ⚠️ Save These Codes
                  </p>
                  <p className="text-xs text-amber-700">
                    Store these backup codes in a safe place. Each can be used once if you lose access to your device.
                  </p>
                </div>

                <div className="grid grid-cols-2 gap-2">
                  {backupCodes.map((code, index) => (
                    <button
                      key={index}
                      onClick={() => copyToClipboard(code, index)}
                      className="p-2 bg-gray-50 rounded border hover:bg-gray-100 transition-colors"
                    >
                      <div className="flex items-center justify-between gap-2">
                        <code className="text-xs font-mono">{code}</code>
                        {copiedCode === index ? (
                          <Check className="w-3 h-3 text-green-600" />
                        ) : (
                          <Copy className="w-3 h-3 text-gray-400" />
                        )}
                      </div>
                    </button>
                  ))}
                </div>

                <Button onClick={handleFinishSetup} className="w-full bg-green-600 hover:bg-green-700">
                  I've Saved My Backup Codes
                </Button>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
